server: 
  port: 8888

web:
  resource-path: /home/web/Desktop/Java-Sec/代码审计/dreamer_cms-Previous_Releases_4.0.0/src/main/resources/db/dreamer-cms/

spring: 
  datasource: 
    name: dev
    url: jdbc:mysql://127.0.0.1:3306/dreamer-cms?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull
    username: root
    password: Root123
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 2000
    database: 0
    password:
    jedis:
      pool:
        max-idle: 100
        min-idle: 50
        max-wait: -1

# 日志配置
logging:
  level:
    root: info
  file:
    path: /tmp/dreamer-cms/logs/